### ISSUE TITLE
configuration date format incorrect

### ISSUE THREAD

**Issue by manuelesquivias** [britned/empire-platform-api#4]
### Description
Using `empire-platform-api-public-client` python package, I was trying to fetch public auctions filtering by delivery start date, with a python native datetime object and an `APIException` is raised

### Environment
- __Package version__: empire-platform-api-public-client 1.0.2
- __Python version__: python 3.10.6
- __Operating system__: Ubuntu 22.04

### Additional context
I am missing an API Key but I am pretty sure it is not the issue because I can fetch public auctions without delivery period start.

### Code sample
```python
import datetime

from empire_platform_api_public_client import *

configuration = Configuration(
    host="https://api.training.empire.britned.com",
    api_key={"ApiKey": "<empire api key>"},
)

api_client = ApiClient(configuration=configuration)


public_auctions_api = PublicAuctionApi(api_client=api_client)


auctions = public_auctions_api.get_public_auctions(
    limit=20,
    offset=0,
    sort_by=AuctionSortBy.BIDDING_PERIOD_START_ASC,
    delivery_period_start=datetime.datetime(2023, 9, 14),
)


print(auctions)
```
This code raises an exception:
```shell
empire_platform_api_public_client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 14 Sep 2023 08:24:11 GMT', 'Content-Type': 'application/json', 'Content-Length': '120', 'Connection': 'keep-alive', 'x-content-type-options': 'nosniff, nosniff', 'x-xss-protection': '1; mode=block, 1; mode=block', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'pragma': 'no-cache', 'expires': '0', 'strict-transport-security': 'max-age=31536000 ; includeSubDomains, max-age=31536000 ; includeSubDomains', 'x-frame-options': 'DENY, deny', 'x-envoy-upstream-service-time': '3', 'server': 'istio-envoy', 'content-security-policy': "default-src 'self'; frame-src 'self'; frame-ancestors 'self'; object-src 'none';", 'feature-policy': "camera 'none'; microphone 'none'; geolocation 'none'; encrypted-media 'none'; payment 'none'; speaker 'none'; usb 'none';", 'permissions-policy': 'camera=(), microphone=(), geolocation=(), encrypted-media=(), payment=(), usb=()', 'referrer-policy': 'no-referrer', 'x-dns-prefetch-control': 'off', 'x-download-options': 'noopen'})
HTTP response body: {"requestId":null,"message":"Invalid parameter.","code":"BAD_REQUEST","nestedErrors":null,"params":{},"debugError":null}
```

### Possible fix
I realised looking into the package code the `empire-platform-api-public-client.configuration.py@201` file contains this:

```python
self.datetime_format = "%Y-%m-%dT%H:%M:%S.%f%z"
```
I suspect this string format is not being correctly parsed by the Empire API, but if I change it to:

```python
self.datetime_format = "%Y-%m-%dT%H:%M:%S.%fZ"
```
The code works perfectly

**Comment by exoszajzbuk** [comment]
@manuelesquivias thank you for pointing it out and writing a suggestion/solution!

we'll have a look into it and schedule a fix if for the next feature-release after Empire went live (coming sometime october)

**Comment by exoszajzbuk** [comment]
@manuelesquivias we've looked into the issue and figured that the `datetime.datetime(2023, 9, 14)` constructor by default does not attach any timezone information for the resulting object, which cannot and will not be consumed by the API by design

can you please try explicitly set the timezone and confirm if it works for you?

```python
auctions = public_auctions_api.get_public_auctions(
    limit=20,
    offset=0,
    sort_by=AuctionSortBy.BIDDING_PERIOD_START_ASC,
    delivery_period_start=datetime.datetime(2023, 9, 14, 0, 0, 0, 0, datetime.timezone.utc),
)
```

---

in the meantime another issue surfaced in #5 with not importing `date` and `datetime` correctly, which will indeed need a fix in the coming 1.1.0 version

**Comment by manuelesquivias** [comment]
Still having the same issue

Updated code:
```python
import datetime

from empire_platform_api_public_client import *

configuration = Configuration(
    host="https://api.training.empire.britned.com",
    api_key={"ApiKey": "<empire api key>"},
)

api_client = ApiClient(configuration=configuration)


public_auctions_api = PublicAuctionApi(api_client=api_client)


auctions = public_auctions_api.get_public_auctions(
    limit=20,
    offset=0,
    sort_by=AuctionSortBy.BIDDING_PERIOD_START_ASC,
    delivery_period_start=datetime.datetime(
        2023, 9, 14, 0, 0, 0, 0, datetime.timezone.utc
    ),
)


print(auctions)
```
Traceback exception:

```
Traceback (most recent call last):
  File "/home/manuel/dev/empire-gw/test.py", line 18, in <module>
    auctions = public_auctions_api.get_public_auctions(
  File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
  File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
  File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
  File "/home/manuel/.cache/pypoetry/virtualenvs/empire-gw-ccZdoRav-py3.10/lib/python3.10/site-packages/empire_platform_api_public_client/api/public_auction_api.py", line 253, in get_public_auctions
    return self.get_public_auctions_with_http_info(limit, offset, sort_by, border_direction, timescale, product_type, status, bidding_period_start, bidding_period_end, delivery_period_start, delivery_period_end, query, **kwargs)  # noqa: E501
  File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
  File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
  File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
  File "/home/manuel/.cache/pypoetry/virtualenvs/empire-gw-ccZdoRav-py3.10/lib/python3.10/site-packages/empire_platform_api_public_client/api/public_auction_api.py", line 427, in get_public_auctions_with_http_info
    return self.api_client.call_api(
  File "/home/manuel/.cache/pypoetry/virtualenvs/empire-gw-ccZdoRav-py3.10/lib/python3.10/site-packages/empire_platform_api_public_client/api_client.py", line 407, in call_api
    return self.__call_api(resource_path, method,
  File "/home/manuel/.cache/pypoetry/virtualenvs/empire-gw-ccZdoRav-py3.10/lib/python3.10/site-packages/empire_platform_api_public_client/api_client.py", line 222, in __call_api
    raise e
  File "/home/manuel/.cache/pypoetry/virtualenvs/empire-gw-ccZdoRav-py3.10/lib/python3.10/site-packages/empire_platform_api_public_client/api_client.py", line 212, in __call_api
    response_data = self.request(
  File "/home/manuel/.cache/pypoetry/virtualenvs/empire-gw-ccZdoRav-py3.10/lib/python3.10/site-packages/empire_platform_api_public_client/api_client.py", line 433, in request
    return self.rest_client.get_request(url,
  File "/home/manuel/.cache/pypoetry/virtualenvs/empire-gw-ccZdoRav-py3.10/lib/python3.10/site-packages/empire_platform_api_public_client/rest.py", line 240, in get_request
    return self.request("GET", url,
  File "/home/manuel/.cache/pypoetry/virtualenvs/empire-gw-ccZdoRav-py3.10/lib/python3.10/site-packages/empire_platform_api_public_client/rest.py", line 234, in request
    raise ApiException(http_resp=r)
empire_platform_api_public_client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 26 Sep 2023 09:13:12 GMT', 'Content-Type': 'application/json', 'Content-Length': '120', 'Connection': 'keep-alive', 'x-content-type-options': 'nosniff, nosniff', 'x-xss-protection': '1; mode=block, 1; mode=block', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'pragma': 'no-cache', 'expires': '0', 'strict-transport-security': 'max-age=31536000 ; includeSubDomains, max-age=31536000 ; includeSubDomains', 'x-frame-options': 'DENY, deny', 'x-envoy-upstream-service-time': '3', 'server': 'istio-envoy', 'content-security-policy': "default-src 'self'; frame-src 'self'; frame-ancestors 'self'; object-src 'none';", 'feature-policy': "camera 'none'; microphone 'none'; geolocation 'none'; encrypted-media 'none'; payment 'none'; speaker 'none'; usb 'none';", 'permissions-policy': 'camera=(), microphone=(), geolocation=(), encrypted-media=(), payment=(), usb=()', 'referrer-policy': 'no-referrer', 'x-dns-prefetch-control': 'off', 'x-download-options': 'noopen'})
HTTP response body: {"requestId":null,"message":"Invalid parameter.","code":"BAD_REQUEST","nestedErrors":null,"params":{},"debugError":null}
```

**Comment by exoszajzbuk** [comment]
confirmed, looks like the backend is not accepting the otherwise correct `2023-09-14T00:00:00.000000+0000` string including the timezone information

**Comment by exoszajzbuk** [comment]
@manuelesquivias We've managed to fix the issue in the 1.1.0 version of the SDK. We've completely removed the configuration option

```python
self.datetime_format = "%Y-%m-%dT%H:%M:%S.%f%z"
```

because it was a bit misleading anyways, it was [only applied to query params](https://github.com/OpenAPITools/openapi-generator/issues/16284), and nowhere else in the generated SDK. Now a simple `.isoformat()` call is used to format query strings instead which will output in a ISO 8601 format which is consumed by the backend (using the `+00:00` suffix instead of `+0000`)

The Backend implementing the full 1.1.0 feature set of the API is only scheduled to be deployed on the TRAINING environment on 2023-11-08, but you can validate the fix using the 1.1.0 SDK using the existing features.

**Comment by exoszajzbuk** [comment]
@manuelesquivias please also note, that timezone-aware `datetime`-s are indeed required to be used, as it has been added to the [relevant README section](https://github.com/britned/empire-platform-api#-python-client-sdk)

**Comment by exoszajzbuk** [comment]
@manuelesquivias the 1.1.0 release of the platform (implementing API version 1.1.0) has been deployed on the TRAINING environment yesterday

can you please re-test your issue and confirm if it is fixed?
